/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_example_administrator_myjni_MainActivity */

#ifndef _Included_com_example_administrator_myjni_MainActivity
#define _Included_com_example_administrator_myjni_MainActivity
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_example_administrator_myjni_MainActivity
 * Method:    stringFromJNI
 * Signature: ()Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_com_example_administrator_myjni_MainActivity_stringFromJNI
  (JNIEnv *, jobject);

/*
 * Class:     com_example_administrator_myjni_MainActivity
 * Method:    FromatstringFromJNI
 * Signature: (Ljava/lang/String;)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_com_example_administrator_myjni_MainActivity_FromatstringFromJNI
  (JNIEnv *, jobject, jstring);

#ifdef __cplusplus
}
#endif
#endif
